### ISSUE TITLE
What is the recommended means for configuring the database?

### ISSUE THREAD

**Issue by hesco** [houstonmc/houston#125]
config/database.yml includes incomplete database credentials.  
my postgres server is not at localhost.  
does this thing support a complete database connection?  
what is the recommended means for its configuration?

-- Hugh 

```
root@houston:/opt/local/houston# bundle exec rake db:seed                                                                                                                
/opt/local/houston/vendor/ruby/2.2.0/gems/htmlentities-4.3.2/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
[config] default host: localhost:3000
Skipping timers since we're not running as a server
rake aborted!
PG::ConnectionBad: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `initialize'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `new'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `connect'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/postgresql_adapter.rb:568:in `initialize'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/connection_handling.rb:87:in `connection'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/migration.rb:916:in `initialize'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/migration.rb:829:in `new'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/migration.rb:829:in `open'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/railties/databases.rake:157:in `block (2 levels) in <top (required)>'
/opt/local/houston/vendor/ruby/2.2.0/gems/activerecord-4.1.10/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:abort_if_pending_migrations
(See full trace by running task with --trace)

```

**Comment by hesco** [comment]
Curious to know if this documents the right interface for the database connection:

PG::Connection.new(host, port, options, tty, dbname, user, password) → conn	
http://deveiate.org/code/pg/PGconn.html

Not sure yet how it is that the connection parameters are being read and used.

**Comment by hesco** [comment]
OK.  That seems to have worked:

```
PG::ConnectionBad: FATAL:  no pg_hba.conf entry for host "10.0.1.71", user "houston_poc", database "houston_poc", SSL on
FATAL:  no pg_hba.conf entry for host "10.0.1.71", user "houston_poc", database "houston_poc", SSL off
```

It would be nice to document that little tidbit in the README.md file for the next person.  

I'm guessing, but have not tested, that this application expects to be able to create its own schema.  
Reading these details in the docs would likely save me much time and speculation.

**Comment by boblail** [comment]
Sorry! Yeah, this makes more sense if you're familiar with Rails...

[Here's the Rails Guide](http://guides.rubyonrails.org/configuring.html#configuring-a-database) for `config/database.yml`.
